//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffID { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string Suffix { get; set; }
        public Nullable<bool> AlternateGoesBy { get; set; }
        public string FamiliarFName { get; set; }
        public string FamiliarLName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Cell { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> Administrative { get; set; }
        public string EmergencyName { get; set; }
        public string EmergencyRelation { get; set; }
        public string EmergencyPhone { get; set; }
        public string Allergies { get; set; }
        public string Gender { get; set; }
        public Nullable<int> PositionTypeID { get; set; }
        public Nullable<bool> Technical { get; set; }
        public string Certificate { get; set; }
        public Nullable<bool> Associates { get; set; }
        public string ADegree { get; set; }
        public Nullable<bool> Bachelors { get; set; }
        public string BDegree { get; set; }
        public Nullable<bool> Masters { get; set; }
        public string MDegree { get; set; }
        public Nullable<bool> Doctorate { get; set; }
        public string DDegree { get; set; }
        public Nullable<bool> Specialist { get; set; }
        public string SDegree { get; set; }
        public Nullable<bool> Military { get; set; }
        public string Branch { get; set; }
        public string OtherEd { get; set; }
        public Nullable<int> HealthID { get; set; }
        public string HPersonType { get; set; }
        public string HCoveredName { get; set; }
        public Nullable<bool> HRemoved { get; set; }
        public Nullable<System.DateTime> HDateStart { get; set; }
        public Nullable<System.DateTime> HDateRemoved { get; set; }
        public Nullable<int> DentalID { get; set; }
        public string DPersonType { get; set; }
        public string DCoveredName { get; set; }
        public Nullable<bool> DRemoved { get; set; }
        public Nullable<System.DateTime> DDateStart { get; set; }
        public Nullable<System.DateTime> DDateRemoved { get; set; }
        public Nullable<bool> LifeI { get; set; }
        public Nullable<bool> SuppLife { get; set; }
        public Nullable<System.DateTime> DisibilityDateEligable { get; set; }
        public Nullable<bool> ADandD { get; set; }
        public Nullable<bool> ADDEmployeeSpouse { get; set; }
        public Nullable<bool> ADDEmployeeChild { get; set; }
        public Nullable<bool> AddFamily { get; set; }
        public Nullable<System.DateTime> RetirementEligDate { get; set; }
        public string RetirementContribution { get; set; }
        public Nullable<bool> RetirementMax { get; set; }
        public Nullable<bool> RetirementCatchUp { get; set; }
        public string SRA { get; set; }
        public Nullable<bool> SRAChange { get; set; }
        public Nullable<System.DateTime> SRAChangeDate { get; set; }
        public string Status { get; set; }
        public Nullable<bool> CurrentEmployee { get; set; }
        public Nullable<bool> Retired { get; set; }
        public Nullable<System.DateTime> DateRetired { get; set; }
        public Nullable<bool> COBRA { get; set; }
        public Nullable<System.DateTime> COBRAEligableTo { get; set; }
        public Nullable<System.DateTime> HealthTerminationDate { get; set; }
        public Nullable<bool> Terminated { get; set; }
        public Nullable<bool> Resigned { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string ReasonForLeaving { get; set; }
        public string LastSupervisor { get; set; }
        public string Notes { get; set; }
        public string Room { get; set; }
        public string Extension { get; set; }
        public string HomeOfficePhone { get; set; }
        public string HomeOfficeFax { get; set; }
        public Nullable<bool> FullTime { get; set; }
        public Nullable<bool> PartTime { get; set; }
        public Nullable<bool> OffSite { get; set; }
        public Nullable<bool> CreditCard { get; set; }
        public Nullable<bool> CallingCard { get; set; }
        public Nullable<bool> Computer { get; set; }
        public Nullable<bool> PrinterFax { get; set; }
        public Nullable<System.DateTime> StartAnnual { get; set; }
        public Nullable<System.DateTime> StartSick { get; set; }
        public Nullable<System.DateTime> StartPetty { get; set; }
        public string Spouse { get; set; }
        public string Dependents { get; set; }
        public Nullable<bool> CollectDisability { get; set; }
        public Nullable<System.DateTime> DisibilityStartDate { get; set; }
        public string InsuranceNote { get; set; }
        public string LengthOfService { get; set; }
        public Nullable<System.DateTime> LOSUpdate { get; set; }
        public Nullable<System.DateTime> NinetyDayReviewDate { get; set; }
        public Nullable<bool> NinetyDayReview { get; set; }
        public string Photofile { get; set; }
        public Nullable<bool> Traveling { get; set; }
        public string StaffADandDamount { get; set; }
        public Nullable<System.DateTime> FifteenMonthDate { get; set; }
        public Nullable<System.DateTime> FiveYearDate { get; set; }
        public Nullable<float> ThisYearAnnualLeave { get; set; }
        public Nullable<float> SickLeave { get; set; }
        public Nullable<float> PettyLeave { get; set; }
        public Nullable<System.DateTime> StartMonthDate { get; set; }
        public Nullable<float> RemainingAnnual { get; set; }
        public Nullable<float> RemainingSick { get; set; }
        public Nullable<float> RemainingPetty { get; set; }
        public Nullable<float> OldSickLeave { get; set; }
        public string FunctionalArea { get; set; }
        public string WorkEmail { get; set; }
    }
}
